version: '3'
services:
  bot:
    build: .
    environment:
      PGUSER: jk
      PGHOST: db
      PGPASSWORD: secret
      PGDATABASE: discordbot
      PGPORT: 5432
    container_name: bot
    volumes:
      - ".:/app"
    links:
      - db:db
    restart: always
  db:
    image: kiasaki/alpine-postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: jk
      POSTGRES_DB: discordbot
    ports:
      - 5432:5432
    container_name: db
    restart: always