version: '3'
services:
  bot:
    build: .
    container_name: bot
    volumes:
      - ".:/app"
    links:
      - db:db
  db:
    image: kiasaki/alpine-postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: jk
      POSTGRES_DB: discordbot
    expose:
      - "5432"
    container_name: db